name: 🚀 Deploy website on push

on:
   push:
      branches:
         - main
jobs:
   web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
         - name: 🚚 Get latest code
           uses: actions/checkout@v4

         - name: 📂 Sync files to API ESTOQUE
           if: github.ref == 'refs/heads/main'
           uses: SamKirkland/FTP-Deploy-Action@v4.3.5
           with:
              server: ${{ secrets.FTP_HOST }}
              username: ${{secrets.PROD_FTP_USER}}
              password: ${{secrets.PROD_FTP_PASSWORD}}